### ISSUE TITLE
absolute unix paths cant be passed as value

### ISSUE THREAD

**Issue by fredlllll** [akesseler/Plexdata.ArgumentParser#13]
heyo, i just encountered this issue

--argument /home/x/somefile

results in an exception thrown here
https://github.com/akesseler/Plexdata.ArgumentParser/blob/f729e2cccfe65d8516b6895a7d89a3c9899b285d/code/src/Plexdata.ArgumentParser.NET/Processors/ArgumentProcessor.cs#L453

cause by this line
https://github.com/akesseler/Plexdata.ArgumentParser/blob/f729e2cccfe65d8516b6895a7d89a3c9899b285d/code/src/Plexdata.ArgumentParser.NET/Extensions/ProcessingExtension.cs#L151

wrongly interpreting the path as a parameter. 

the same behaviour would also occur if i try to pass any string in as value that begins with -- or -

a possible fix might be to parse the parameters backwards? so if you encounter a /xyz you check if its a known option, and if not put it on the stack as a value or positional argument, then parse the one before it to see how to interpret the value. or alternatively just trust that the string following a parameter is supposed to be interpreted as value?

**Comment by akesseler** [comment]
Sorry for that late answer...

The reason is an internal check if the option value can be considered as a parameter. A parameter is characterized either by "--", or "-" or even by "/" (Window style). In your concrete use case that safety check fits and in turn causes the exception. 

Against this background, it would not be possible to just fix your particular issue. But a workaround could be to double-quote the option like that:

```
program --argument "/home/x/somefile"
```

Thanks a lot and best regards

**Comment by fredlllll** [comment]
the double quotes get swallowed by the terminal. so not a viable workaround =/ ill sadly have to use a different argument parser
